# WARNING:
# Do not use this file as a template for you repository TravisCI configuration
# Instead use the files under the "/sample_files" directory for that purpose.
language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      
sudo: True

virtualenv:
  system_site_packages: true

env:

  global:
  - VERSION="8.0" ODOO_REPO="odoo/odoo" UNIT_TEST="0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="0"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

install:
  - git clone --depth=1 https://github.com/Jayani/school_management_system.git ${HOME}/school_management_system
  - export PATH=${HOME}/school_management_system/travis:${PATH}

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
